name: CI

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner-os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.runner-os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        global-json-file: global.json

    - name: dotnet format
      run: dotnet format src/OctoshiftCLI.sln --verify-no-changes

    - name: Restore dependencies
      run: dotnet restore src/OctoshiftCLI.sln

    - name: Build
      run: dotnet build src/OctoshiftCLI.sln --no-restore /p:TreatWarningsAsErrors=true

    - name: Unit Test
      run: dotnet test src/OctoshiftCLI.Tests/OctoshiftCLI.Tests.csproj --no-build --verbosity normal --logger:"junit;LogFilePath=unit-tests.xml" --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Copy Coverage To Predictable Location
      if: always() && matrix.runner-os == 'ubuntu-latest'
      run: cp coverage/**/coverage.cobertura.xml coverage/coverage.cobertura.xml

    # This is used by the subsequent publish-test-results.yml
    - name: Upload Unit Test Results
      if: always() && matrix.runner-os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: Unit Test Results
        path: src/OctoshiftCLI.Tests/unit-tests.xml

    # This is used by the subsequent publish-test-results.yml
    - name: Upload Code Coverage Report
      if: always() && matrix.runner-os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: Code Coverage Report
        path: code-coverage-results.md
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      if: matrix.runner-os == 'ubuntu-latest'

  upload-event-file:
    runs-on: ubuntu-latest
    steps:
    # This is used by the subsequent publish-test-results.yaml
    - name: Upload Event File
      uses: actions/upload-artifact@v3
      with:
        name: Event File
        path: ${{ github.event_path }}

  build-for-e2e-test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login == 'github'
    strategy:
      fail-fast: false
      matrix:
        target-os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build Artifacts (Linux)
      if: matrix.target-os == 'ubuntu-latest'
      run: ./publish.ps1
      shell: pwsh
      env:
        SKIP_WINDOWS: "true"
        SKIP_MACOS: "true"

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries-${{ matrix.target-os }}
        path: |
          dist/linux-x64/ado2gh-linux-amd64
          dist/linux-x64/bbs2gh-linux-amd64
          dist/linux-x64/gei-linux-amd64
          dist/osx-x64/ado2gh-darwin-amd64
          dist/osx-x64/bbs2gh-darwin-amd64
          dist/osx-x64/gei-darwin-amd64
          dist/win-x64/ado2gh-windows-amd64.exe
          dist/win-x64/bbs2gh-windows-amd64.exe
          dist/win-x64/gei-windows-amd64.exe
